### ISSUE TITLE
pdjBot Commands Not Ported Over

### ISSUE THREAD

**Issue by martindale** [martindale/snarl#26]
Various functions and commands from [unusualbob/pdjBot](http://github.com/unusualbob/pdjBot) need to be merged in.

**Comment by mikemimik** [comment]
Which functions and commands?

**Comment by martindale** [comment]
Obviously the most important one is [catfacts](https://github.com/unusualbob/pdjBot/blob/master/bot.js#L292).

Most of the others (all in that same switch/case statement) appear specific to plug.dj, so this issue is almost entirely resolved.  Maybe this is an opportunity for a new `catfacts` plugin, and we can close this when published?
